@Library('jenkins-shared-library-demo') _

pipeline {
    agent any

    parameters {
        choice(name: 'TARGET_ENV', choices: ['dev', 'prod'], description: 'Select the environment')
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Terraform action')
    }

    stages {
        stage('Terraform Deploy (Shared Library)') {
            steps {
                script {
                    terraformPipeline(
                        env: params.TARGET_ENV,
                        action: params.ACTION,
                        credId: 'aws-ecr-creds',
                        dir: "aws-free-tier-project/terraform/${params.TARGET_ENV}",
                        tfvars: "${params.TARGET_ENV}.tfvars"
                    )
                }
            }
        }
    }
}
