@Library('jenkins-shared-library-demo') _

pipeline {
    agent any

    parameters {
        choice(name: 'TARGET_ENV', choices: ['dev', 'prod', 'all'], description: 'Choose environment')
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Terraform Action')
    }

    stages {

        stage('Deploy Dev Environment') {
            when {
                anyOf {
                    expression { params.TARGET_ENV == 'dev' }
                    expression { params.TARGET_ENV == 'all' }
                }
            }
            steps {
                script {
                    terraformPipeline(
                        env: 'dev',
                        action: params.ACTION,
                        credId: 'aws-ecr-creds',
                        dir: "aws-free-tier-project/terraform/dev",
                        tfvars: "dev.tfvars"
                    )
                }
            }
        }

        stage('Deploy Prod Environment') {
            when {
                anyOf {
                    expression { params.TARGET_ENV == 'prod' }
                    expression { params.TARGET_ENV == 'all' }
                }
            }
            steps {
                script {
                    terraformPipeline(
                        env: 'prod',
                        action: params.ACTION,
                        credId: 'aws-ecr-creds',
                        dir: "aws-free-tier-project/terraform/prod",
                        tfvars: "prod.tfvars"
                    )
                }
            }
        }
    }

    post {
        always {
            echo '🧹 Cleaning workspace...'
            cleanWs()
        }
    }
}
